replace cjson with json-c
* pwrevents: Add missing includes when building with json-c
  Fails when json-c is used instead of cjson.
  src/pwrevents/client.c:277:3: error: implicit declaration of function 'strcmp'
  src/pwrevents/suspend_ipc.c:142:2: error: implicit declaration of function 'strlen'
  src/pwrevents/shutdown.c:579:3: error: implicit declaration of function 'strcmp'

* debug.h: Rename to sleepd_debug.h
  json-c is also staging debug.h and wrong one is used in builds where
  json-c is used instead of cjson.
  json-c include paths appear before include/internal and build fails
  with:
  2.0.0-35-r6/git/src/utils/wait.c: In function 'WaitObjectWaitTimeSpec':
  2.0.0-35-r6/git/src/utils/wait.c:126:9: error: implicit declaration of
     function 'TRACE' [-Werror=implicit-function-declaration]
           TRACE("%s: Error getting monotonic clock, "
           ^
  2.0.0-35-r6/git/src/pwrevents/shutdown.c: In function
    'client_vote_clear':
  2.0.0-35-r6/git/src/pwrevents/shutdown.c:277:2: error: implicit
    declaration of function '_assert'
    [-Werror=implicit-function-declaration]
    _assert(client != NULL);
    ^

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>